In [1]:
# Import Dependencies
import pandas as pd
import numpy as np

In [2]:
csv_path = "Data/Merged_Year_Data/data_2015.csv"
data_2015_df = pd.read_csv(csv_path)
data_2015_df.head()

,State,"Honey producing colonies/1,000",Yield per colony (pounds),"Production (1,000 pounds)","Stocks December 15 (1,000 pounds)",Average price per pound (dollars),"Value of production (1,000 dollars)",Year,Colony_Number,Max_Colony_Number,Lost_Colony_Number,Added_Colony_Number,Renovated_Colony_Number,VarroaMites_Percent,Other_Pests_Parasites_Percent,Diseases_Percent,Pesticides_Percent,Other_Percent,Unknown_Percent
0,Alabama,7.0,47.0,329.0,13.0,383.0,1260.0,2015,31000.0,31500.0,4670.0,4940.0,1250.0,23.225,31.225,0.200,1.825000,4.325,8.275
1,Arizona,26.0,49.0,1274.0,306.0,217.0,2765.0,2015,144000.0,147000.0,28100.0,30200.0,40600.0,34.725,19.775,1.775,13.633333,9.525,6.000
2,Arkansas,24.0,72.0,1728.0,121.0,202.0,3491.0,2015,72500.0,84500.0,14800.0,15100.0,5800.0,47.700,29.225,2.375,9.800000,9.675,3.075
3,California,275.0,30.0,8250.0,1485.0,204.0,16830.0,2015,3960000.0,4800000.0,584000.0,499000.0,577000.0,38.200,15.450,7.375,15.450000,11.550,4.475
4,Colorado,29.0,51.0,1479.0,399.0,218.0,3224.0,2015,68500.0,91500.0,10400.0,11000.0,5040.0,37.825,7.150,7.575,9.900000,4.525,4.250

In [3]:
csv_path = "Data/Merged_Year_Data/data_2016.csv"
data_2016_df = pd.read_csv(csv_path)
data_2016_df.head()

,State,"Honey producing colonies/1,000",Yield per colony (pounds),"Production (1,000 pounds)","Stocks December 15 (1,000 pounds)",Average price per pound (dollars),"Value of production (1,000 dollars)",Year,Colony_Number,Max_Colony_Number,Lost_Colony_Number,Added_Colony_Number,Renovated_Colony_Number,VarroaMites_Percent,Other_Pests_Parasites_Percent,Diseases_Percent,Pesticides_Percent,Other_Percent,Unknown_Percent
0,Alabama,7.0,52.0,364.0,33.0,345.0,1256.0,2016,30500.0,30500.0,4440.0,2890.0,930.0,14.450,20.525,1.600,4.000,4.275,8.450
1,Arizona,27.0,46.0,1242.0,261.0,197.0,2447.0,2016,111000.0,116000.0,20900.0,24000.0,8260.0,50.275,16.700,6.800,9.925,10.400,5.700
2,Arkansas,24.0,69.0,1656.0,99.0,185.0,3064.0,2016,111000.0,111000.0,12400.0,16990.0,3870.0,61.025,7.300,2.950,2.450,2.275,3.325
3,California,310.0,36.0,11160.0,2009.0,204.0,22766.0,2016,3760000.0,4710000.0,605000.0,488000.0,361000.0,42.975,15.200,9.175,13.900,10.925,4.350
4,Colorado,32.0,40.0,1280.0,282.0,224.0,2867.0,2016,78500.0,103000.0,13370.0,12600.0,1440.0,30.825,7.150,5.175,7.325,7.225,0.175

In [4]:
csv_path = "Data/Merged_Year_Data/data_2017.csv"
data_2017_df = pd.read_csv(csv_path)
data_2017_df.head()

,State,"Honey producing colonies/1,000",Yield per colony (pounds),"Production (1,000 pounds)","Stocks December 15 (1,000 pounds)",Average price per pound (dollars),"Value of production (1,000 dollars)",Year,Colony_Number,Max_Colony_Number,Lost_Colony_Number,Added_Colony_Number,Renovated_Colony_Number,VarroaMites_Percent,Other_Pests_Parasites_Percent,Diseases_Percent,Pesticides_Percent,Other_Percent,Unknown_Percent
0,Alabama,7.0,42.0,294.0,44.0,3.20,941.0,2017.0,28000.0,30500.0,3930.0,3010.0,2260.0,31.250,14.175,4.500,13.175,6.525,6.2
1,Arizona,23.0,46.0,1058.0,201.0,1.97,2084.0,2017.0,106000.0,110000.0,19200.0,21700.0,7300.0,43.700,5.575,6.500,4.150,10.775,2.3
2,Arkansas,20.0,55.0,1100.0,176.0,1.53,1683.0,2017.0,89000.0,91000.0,18900.0,12330.0,2340.0,36.775,16.075,14.500,13.300,10.100,1.6
3,California,335.0,48.0,16080.0,3216.0,1.56,25085.0,2017.0,3560000.0,4490000.0,476000.0,588000.0,505000.0,41.075,12.550,5.875,13.000,9.625,4.8
4,Colorado,32.0,46.0,1472.0,500.0,2.14,3150.0,2017.0,95000.0,126000.0,15900.0,10000.0,17910.0,32.925,1.000,2.700,8.300,7.650,1.8

In [5]:
csv_path = "Data/Merged_Year_Data/data_2018.csv"
data_2018_df = pd.read_csv(csv_path)
data_2018_df.head()

,State,"Honey producing colonies/1,000",Yield per colony (pounds),"Production (1,000 pounds)","Stocks December 15 (1,000 pounds)",Average price per pound (dollars),"Value of production (1,000 dollars)",Year,Colony_Number,Max_Colony_Number,Lost_Colony_Number,Added_Colony_Number,Renovated_Colony_Number,VarroaMites_Percent,Other_Pests_Parasites_Percent,Diseases_Percent,Pesticides_Percent,Other_Percent,Unknown_Percent
0,Alabama,6.0,45.0,270.0,14.0,3.72,1004.0,2018,30000.0,31000.0,4160.0,4310.0,4810.0,37.725,36.400000,1.275000,11.025000,7.825,5.225
1,Arizona,24.0,38.0,912.0,109.0,3.01,2745.0,2018,100500.0,103500.0,21600.0,18210.0,5760.0,39.550,5.550000,11.350000,6.633333,11.125,9.625
2,Arkansas,28.0,50.0,1400.0,84.0,1.88,2632.0,2018,92500.0,93500.0,17300.0,17250.0,3780.0,42.325,10.125000,0.666667,29.225000,5.450,8.325
3,California,335.0,41.0,13735.0,3022.0,2.11,28981.0,2018,3560000.0,4630000.0,533000.0,525000.0,573500.0,46.175,11.175000,7.575000,13.675000,9.600,5.175
4,Colorado,31.0,48.0,1488.0,283.0,2.05,3050.0,2018,93500.0,112000.0,15700.0,12770.0,9770.0,55.075,7.766667,5.875000,2.366667,8.150,2.125

In [6]:
csv_path = "Data/Merged_Year_Data/data_2019.csv"
data_2019_df = pd.read_csv(csv_path)
data_2019_df.head()

,State,"Honey producing colonies/1,000",Yield per colony (pounds),"Production (1,000 pounds)","Stocks December 15 (1,000 pounds)",Average price per pound (dollars),"Value of production (1,000 dollars)",Year,Colony_Number,Max_Colony_Number,Lost_Colony_Number,Added_Colony_Number,Renovated_Colony_Number,VarroaMites_Percent,Other_Pests_Parasites_Percent,Diseases_Percent,Pesticides_Percent,Other_Percent,Unknown_Percent
0,Alabama,7.0,42.0,294.0,44.0,3.20,941.0,2019,18500.0,18500.0,2300.0,1200.0,600.0,34.833333,24.666667,1.766667,1.800000,7.266667,8.900000
1,Arizona,23.0,46.0,1058.0,201.0,1.97,2084.0,2019,82000.0,88000.0,11500.0,6230.0,4190.0,36.233333,6.433333,3.200000,16.966667,8.533333,1.233333
2,Arkansas,20.0,55.0,1100.0,176.0,1.53,1683.0,2019,67000.0,68500.0,10200.0,620.0,1010.0,40.133333,20.300000,3.833333,37.866667,6.700000,25.000000
3,California,335.0,48.0,16080.0,3216.0,1.56,25085.0,2019,2490000.0,3580000.0,464000.0,330000.0,231000.0,44.333333,11.933333,6.766667,13.200000,9.266667,4.600000
4,Colorado,32.0,46.0,1472.0,500.0,2.14,3150.0,2019,65000.0,70500.0,17820.0,3300.0,3840.0,52.900000,4.766667,4.800000,12.750000,4.833333,0.800000

In [7]:
merge_all_df = pd.concat((data_2015_df, data_2016_df, data_2017_df, data_2018_df, data_2019_df))
merge_all_df

,State,"Honey producing colonies/1,000",Yield per colony (pounds),"Production (1,000 pounds)","Stocks December 15 (1,000 pounds)",Average price per pound (dollars),"Value of production (1,000 dollars)",Year,Colony_Number,Max_Colony_Number,Lost_Colony_Number,Added_Colony_Number,Renovated_Colony_Number,VarroaMites_Percent,Other_Pests_Parasites_Percent,Diseases_Percent,Pesticides_Percent,Other_Percent,Unknown_Percent
0,Alabama,7.0,47.0,329.0,13.0,383.0,1260.0,2015.0,31000.0,31500.0,4670.0,4940.0,1250.0,23.225000,31.225000,0.200000,1.825000,4.325000,8.275000
1,Arizona,26.0,49.0,1274.0,306.0,217.0,2765.0,2015.0,144000.0,147000.0,28100.0,30200.0,40600.0,34.725000,19.775000,1.775000,13.633333,9.525000,6.000000
2,Arkansas,24.0,72.0,1728.0,121.0,202.0,3491.0,2015.0,72500.0,84500.0,14800.0,15100.0,5800.0,47.700000,29.225000,2.375000,9.800000,9.675000,3.075000
3,California,275.0,30.0,8250.0,1485.0,204.0,16830.0,2015.0,3960000.0,4800000.0,584000.0,499000.0,577000.0,38.200000,15.450000,7.375000,15.450000,11.550000,4.475000
4,Colorado,29.0,51.0,1479.0,399.0,218.0,3224.0,2015.0,68500.0,91500.0,10400.0,11000.0,5040.0,37.825000,7.150000,7.575000,9.900000,4.525000,4.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44,Massachusetts,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,22300.0,22300.0,2980.0,920.0,710.0,10.300000,1.550000,0.500000,4.300000,2.700000,6.300000
45,New Mexico,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,13200.0,16300.0,410.0,1030.0,560.0,16.066667,10.166667,0.633333,NaN,1.600000,0.300000
46,Oklahoma,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,35000.0,99500.0,3480.0,610.0,1100.0,12.566667,0.700000,0.100000,0.250000,2.250000,2.250000
47,Other States 5/,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,30740.0,31480.0,4010.0,670.0,930.0,NaN,NaN,NaN,NaN,NaN,NaN
48,Other States 4/,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,NaN,NaN,NaN,NaN,10.600000,2.866667,1.600000,4.000000,11.966667,0.866667

In [9]:
merge_all_df = merge_all_df.sort_values(['State'])
merge_all_df

,State,"Honey producing colonies/1,000",Yield per colony (pounds),"Production (1,000 pounds)","Stocks December 15 (1,000 pounds)",Average price per pound (dollars),"Value of production (1,000 dollars)",Year,Colony_Number,Max_Colony_Number,Lost_Colony_Number,Added_Colony_Number,Renovated_Colony_Number,VarroaMites_Percent,Other_Pests_Parasites_Percent,Diseases_Percent,Pesticides_Percent,Other_Percent,Unknown_Percent
0,Alabama,7.0,47.0,329.0,13.0,383.00,1260.0,2015.0,31000.0,31500.0,4670.0,4940.0,1250.0,23.225000,31.225000,0.200000,1.825000,4.325000,8.275000
0,Alabama,7.0,52.0,364.0,33.0,345.00,1256.0,2016.0,30500.0,30500.0,4440.0,2890.0,930.0,14.450000,20.525000,1.600000,4.000000,4.275000,8.450000
0,Alabama,7.0,42.0,294.0,44.0,3.20,941.0,2019.0,18500.0,18500.0,2300.0,1200.0,600.0,34.833333,24.666667,1.766667,1.800000,7.266667,8.900000
0,Alabama,7.0,42.0,294.0,44.0,3.20,941.0,2017.0,28000.0,30500.0,3930.0,3010.0,2260.0,31.250000,14.175000,4.500000,13.175000,6.525000,6.200000
0,Alabama,6.0,45.0,270.0,14.0,3.72,1004.0,2018.0,30000.0,31000.0,4160.0,4310.0,4810.0,37.725000,36.400000,1.275000,11.025000,7.825000,5.225000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,Wyoming,39.0,56.0,2184.0,306.0,1.35,2948.0,2019.0,57500.0,64500.0,6550.0,2600.0,3990.0,24.666667,6.350000,2.200000,2.200000,3.700000,6.000000
39,Wyoming,39.0,56.0,2184.0,175.0,1.91,4171.0,2018.0,77000.0,96000.0,9020.0,5190.0,6200.0,22.800000,2.800000,1.825000,6.033333,2.325000,2.650000
39,Wyoming,39.0,56.0,2184.0,306.0,1.35,2948.0,2017.0,84500.0,112000.0,13700.0,11700.0,7920.0,24.450000,2.433333,7.375000,4.300000,5.425000,2.633333
39,Wyoming,38.0,77.0,2926.0,146.0,190.00,5559.0,2015.0,70500.0,97000.0,9000.0,9800.0,6840.0,23.375000,10.733333,4.600000,5.833333,5.575000,2.233333
39,Wyoming,40.0,68.0,2720.0,190.0,178.00,4842.0,2016.0,66200.0,99000.0,12140.0,9350.0,1580.0,25.966667,1.925000,1.250000,2.725000,1.950000,0.800000

In [10]:
# csv files 
merge_all_df.to_csv('merge_all.csv', index=False, header=True)